"""test

Revision ID: 68828cb52ba9
Revises: 9e845e396829
Create Date: 2024-12-22 00:54:46.555831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68828cb52ba9'
down_revision = '9e845e396829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('connections')
    # ### end Alembic commands ###
